### ISSUE TITLE
Lost of RobotRequest.h in max_min_lp_experiment

### ISSUE THREAD

**Issue by YCH188** [raaslab/multi-robot_task_allocation#1]
Hi, I'm learning the code but I encountered a problem. When I build the project, I found max_min_lp_experiment lose RobortRequest.h and TargetRequest.h.
Could you help fix the problem?Thank you!

**Comment by YCH188** [comment]
Sorry to bother. I found the

**Comment by rvipin17** [comment]
Did you solve this issue?

**Comment by proffessorx** [comment]
I am getting Same issue

**Comment by YCH188** [comment]
@rvipin17 @proffessorx I have catkin_make several times and the problem solved. Because I haven't learned compiling principle I cannot explain why it solved.

**Comment by syc7446** [comment]
This was due to incomplete package (i.e., max\_min\_lp\_experiment) we had worked on previously. Sorry for the confusion. Currently, max\_min\_lp\_experiment package is not available. Take out max\_min\_lp\_experiment from your workspace and do catkin\_make.
